name: build-and-test

on:
  push:
    branches: [ master ]  
    paths:
      - 'src/9.0/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:      
      SOLUTION_PATH: ./src/9.0/
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x            
    - name: Build
      run: dotnet build $SOLUTION_PATH -c Release      
    - name: Test
      run: dotnet test $SOLUTION_PATH -c Release --no-build